- name: enable winrm via vmware
  hosts: all
  gather_facts: no
  become: no
  vars:
    vcenter_ip: 
    vcenter_username: 
    vcenter_password: 
    vm_name: 
    datacenter:
    vm_username:
    vm_password:
    vm_network:
    cluster: 
    
  tasks:
    - name: enable winrm via vCenter
      vmware_vm_shell:
        hostname: "{{ vcenter_ip }}"
        username: "{{  vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        validate_certs: no
        vm_id: "{{ vm_name }}"
        vm_username: "{{ vm_username }}"
        vm_password: "{{ vm_password }}"
        vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
        vm_shell_args:  -command "& $([scriptblock]::Create((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'))) -ForceNewSSLCert -EnableCredSSP"
      delegate_to: localhost
