---
- name: Create a virtual machine on vSphere
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vcenter_ip: 
    vcenter_username: 
    vcenter_password: 
    vm_name: win-server-vm-0001
    template: WinServer2016_templ0001
    guest_domain: ansibleworkshop.com
  
  tasks: 
    - name: Connect to vCenter and Deploy from template
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template }}"
        cluster: Cluster01
        datacenter: DC01
        folder: ansiblevms
        customization:
          domain: "{{ guest_domain }}"
          #dns_servers:
          #  - 8.9.9.9
          #  - 7.8.8.9
          dns_suffix:
            - ansibleworkshop.com
        networks:
        - name: VM Network
        wait_for_ip_address: yes
