---
- hosts: windows
  name: his is my Windows application management playbook
  vars:
    packages:
      - googlechrome
      #- jre8
      - avgantivirusfree

  tasks:
  - name: Install Windows Packages
    win_chocolatey:
      name: "{{ packages }}"
      state: present
      ignore_checksums: true
    become_user: Administrator
    become_method: runas
