---

- name: stop windows update service
  win_service:
    name: wuauserv
    state: stopped

- name: remove windows update settings
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\WindowsUpdate
    name: "{{ item }}"
    state: absent
  loop:
    - SusClientId
    - PingID
    - AccountDomainSid

- name: start windows update service
  win_service:
    name: wuauserv
    state: started

- name: reset the windows update authorization
  win_shell: wuauclt /resetauthorization /detectnow